merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path, include
from listings import views
from listings.views import BandAPIView, ListingAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/band/', BandAPIView.as_view()),
    path('api/listing/', ListingAPIView.as_view()),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/update/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('about/', views.about, name='about'),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:id>/update/', views.listing_update, name='listing-update'),
    path('listings/<int:id>/delete/', views.listing_delete, name='listing-delete'),
    path('contact-us/', views.contact, name='contact'),
    path('email-sent/', views.email_sent, name='email-sent'),
]

merchex/listings/models.py
from random import choices
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):
    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(max_length=50)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2022)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    class Genre(models.TextChoices):
        POP_ROCK = 'PR'
        INDIE = 'IN'
        SOUL = 'SO'
        ALTERNATIVE = 'AL'
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)

    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2022)])
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
    

    class Type(models.TextChoices):
        RECORDS = 'Record'
        CLOTHING = 'Clothing'
        POSTERS = 'Poster'
        MISCELLANEOUS = 'Miscellaneous'
    type = models.fields.CharField(choices=Type.choices, max_length=100)

    def __str__(self):
        return f'{self.title}'

merchex/listings/forms.py
from dataclasses import fields
from django import forms

from listings.models import Band, Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ('active', 'official_homepage')

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        exclude = ('sold',)

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from listings.models import Band, Listing
from listings.forms import ContactUsForm, BandForm, ListingForm

from rest_framework.views import APIView
from rest_framework.response import Response
from listings.serializers import BandSerializer, ListingSerializer

def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html',
    {'bands': bands})

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)

    else:
        form = BandForm()
        return render(request, 'listings/band_create.html', 
        {'form':form})    

def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request, 'listings/band_detail.html', {'band': band})

def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)

    else:
        form = BandForm(instance=band)

    return render(request, 'listings/band_update.html', {'form': form})

def band_delete(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        band.delete()
        return redirect('band_list')

    return render(request, 'listings/band_delete.html', {'band': band})

def about(request):
    return HttpResponse('<h1>A propos...</h1> <p>Nous adorons merch</p>')

def listing_list(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listing_list.html', 
    {'listings': listings})

def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request, 'listings/listing_detail.html', {'listing': listing})

def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)

    else:
        form = ListingForm()
        return render(request, 'listings/listing_create.html', 
        {'form':form}) 

def listing_update(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect('listing-detail', listing.id)

    else:
        form = ListingForm(instance=listing)

    return render(request, 'listings/listing_update.html', {'form': form})

def listing_delete(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        listing.delete()
        return redirect('listing_list')

    return render(request, 'listings/listing_delete.html', {'listing': listing})

def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject= f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message= form.cleaned_data['message'],
                from_email= form.cleaned_data['email'],
                recipient_list= ['admin@merchex.xyz'],
            )
            return redirect('email-sent')

    else:
        form = ContactUsForm()
    return render(request, 'listings/contact.html', 
    {'form': form} )

def email_sent(request):
    return render(request, 'listings/email_sent.html')


class BandAPIView(APIView):
    def get(self, *args, **kwargs):
        bands = Band.objects.all()
        serializer = BandSerializer(bands, many=True)
        return Response(serializer.data)

class ListingAPIView(APIView):
    def get(self, *args, **kwargs):
        listings = Listing.objects.all()
        serializer = ListingSerializer(listings, many=True)
        return Response(serializer.data)

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Ajouter un nouveau groupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer le groupe</h1>

<p>Êtes-vous sûr.e de vouloir supprimer : {{band.name}} ?</p>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>



{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{band.name}}</h2>
<ul>
    <li>Genre: {{band.get_genre_display}}</li>
    <li>Année de formation: {{band.year_formed}} </li>
    <li>Actif: {{band.active|yesno}} </li>
    {% if band.official_homepage %}
    <li><a href="{{band.official_homepage}}">{{band.official_homepage}}</a> </li>
    {% endif %}
</ul>

<p>{{band.biography}} </p>
<p>Annonces liées à ce groupe: </p>
{% for listing in band.listing_set.all %}
<li><a href="{{listing.title}}">{{listing.title}}</a> </li>
{% endfor %}

<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>

<a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>

<a href="{% url 'band-list'%}">Retour à la liste des groupes</a>


{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

<ul>
    {% for band in bands %}
        <li>
            <a href="{% url 'band-detail' band.id%}">{{band.name}}</a>
            <a href="{%  url 'band-update' band.id %}">[Modifier]</a>
        </li>
    {% endfor %}
</ul>


{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mettre le groupe à jour</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Envoyer">
</form>


{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}">
    </head>
    <body>
        <nav>
            <a href="{% url 'band-list'%} ">Groupes</a>
            <a href="{% url 'listing-list'%}">Annonces</a>
            <a href="{% url 'email-sent'%}">Redirection emails</a>
            <a href="{% url 'about'%}">A propos</a>
        </nav>

        {% block content %}
        
        {% endblock %}

    </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<p>Nous sommes là pour vous aider.</p>
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

<p>Votre email a bien été envoyé youpi!</p>


{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Ajouter une nouvelle annonce</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer l'annonce</h1>

<p>Êtes-vous sûr.e de vouloir supprimer : {{listing.title}} ?</p>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>



{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{listing.title}}</h2>
<ul>
    <li>Description: {{listing.description}}</li>
    <li>Année: {{listing.year}} </li>
    <li>Groupe: {{listing.band}} </li>
    <li>Vendu: {{listing.sold|yesno}} </li>
</ul>

<a href="{% url 'listing-list'%}">Retour à toutes les annonces</a>
<a href="{% url 'listing-delete' listing.id %}">Supprimer cette annonce</a>
<a href="{% url 'listing-update' listing.id %}">Modifier cette annonce</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Annonces</h1>

<a href="{% url 'listing-create' %}">Créer une nouvelle annonce</a>

<ul>
    {% for listing in listings %}
        <li>
            <a href="{% url 'listing-detail' listing.id%}">{{listing.title}}</a>
            <a href="{%  url 'listing-update' listing.id %}">[Modifier]</a>
        </li>
    {% endfor %}
</ul>



{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mettre l'annonce' à jour</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Envoyer">
</form>


{% endblock %}